Repository canonical/webteam.canonical.com, pull requests merged in 2022-07, with the labels that each got.

#125 Update team.py
  webapp/team.py
Labels: Review: Code +1

#124 feat: make /practices public
  webapp/sso.py
Labels: Review: Code +1

#127 Update docs template
  konf/site.yaml
  templates/docs.html
  webapp/sso.py
Labels: Review: Code +1, Review: QA +1

#130 Guides: link to discourse
  templates/base.html
  webapp/app.py
  webapp/guides.py
Labels: Review: QA +1, Review: Code +1 (with changes)
